name       : wayland
version    : 1.14.0
release    : 18
source     :
    - https://wayland.freedesktop.org/releases/wayland-1.14.0.tar.xz : ed80cabc0961a759a42092e2c39aabfc1ec9a13c86c98bbe2b812f008da27ab8
license    :
    - MIT
component  : desktop.wayland
emul32     : yes
summary    : Wayland is intended as a simpler replacement for X, easier to develop and maintain.
description: |
    Wayland is a protocol for a compositor to talk to its clients as well as a C library implementation of that protocol. The compositor can be a standalone display server running on Linux kernel modesetting and evdev input devices, an X application, or a wayland client itself. The clients can be traditional applications, X servers (rootless or fullscreen) or other display servers.
builddeps  :
    - pkgconfig32(expat)
    - pkgconfig32(libffi)
    - pkgconfig32(libxml-2.0)
patterns   :
    - devel :
        - /usr/bin
        - /usr/share/wayland
        - /usr/share/aclocal
setup      : |
    %configure --prefix=/usr \
               --disable-static \
               --disable-documentation
build      : |
    %make
install    : |
    %make_install
