name        : wayland
version     : 1.7.0
release     : 10
source      :
    - http://wayland.freedesktop.org/releases/wayland-1.7.0.tar.xz : bdea47a2db96f7e53f1ce0351559c0af5b7f7aae7e95f0a884a78af9f1057c9c
license     :
    - MIT
summary     : Wayland is intended as a simpler replacement for X, easier to develop and maintain.
description : |
    Wayland is a protocol for a compositor to talk to its clients as well as a C library implementation of that protocol. The compositor can be a standalone display server running on Linux kernel modesetting and evdev input devices, an X application, or a wayland client itself. The clients can be traditional applications, X servers (rootless or fullscreen) or other display servers.
patterns   :
    - devel:
        - /usr/bin
        - /usr/share/wayland
        - /usr/share/aclocal
setup      : |
    %configure --disable-static --disable-documentation
build      : |
    %make
install    : |
    %make_install
