name       : wayland
version    : 1.12.0
release    : 17
source     :
    - https://wayland.freedesktop.org/releases/wayland-1.12.0.tar.xz : d6b4135cba0188abcb7275513c72dede751d6194f6edc5b82183a3ba8b821ab1
license    :
    - MIT
summary    : Wayland is intended as a simpler replacement for X, easier to develop and maintain.
description: |
    Wayland is a protocol for a compositor to talk to its clients as well as a C library implementation of that protocol. The compositor can be a standalone display server running on Linux kernel modesetting and evdev input devices, an X application, or a wayland client itself. The clients can be traditional applications, X servers (rootless or fullscreen) or other display servers.
builddeps  :
    - pkgconfig32(expat)
    - pkgconfig32(libffi)
    - pkgconfig32(libxml-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
component  : desktop.wayland
patterns   :
    - devel :
        - /usr/bin
        - /usr/share/wayland
        - /usr/share/aclocal
setup      : |
    %configure --prefix=/usr \
               --disable-static \
               --disable-documentation
build      : |
    %make
install    : |
    %make_install
    %make clean
